spring:
  config:
    active:
      on-profile: nonprod

  kafka:
    producer:
      bootstrap-servers: nonprod:9092,nonprod:9093,nonprod:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer